{% set name = "opentelemetry-instrumentation-haystack" %}
{% set version = "0.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 9d1abf8850777e8bd7005bed76c3f1909161f431eac41ccd7a47598df0b0bcce

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.38.0,<2.0.0
    - opentelemetry-instrumentation >=0.59b0
    - opentelemetry-semantic-conventions >=0.59b0
    - opentelemetry-semantic-conventions-ai >=0.5.1,<0.6.0

# Unable to run tests, haystack-ai has newer version with changes in API in the main channel.
test:
  imports:
    - opentelemetry.instrumentation.haystack
  commands:
    - pip check
  requires:
    - pip
    - haystack-ai
    - haystack-experimental

about:
  home: https://www.traceloop.com/openllmetry
  summary: OpenTelemetry Haystack instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: This library allows tracing complete LLM applications built with Haystack.
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction

extra:
  recipe-maintainers:
    - timkpaine
  skip-lints:
    - invalid_url
    - missing_imports_or_run_test_py